name: Yegeta Barya Habtamu Ministry
markdown: kramdown
plugins:
  - jekyll-coffeescript
compress_html:
  clippings: all
  comments:  ["<!-- ", " -->"]
  endings:   all
plugins:
  - jekyll-sitemap
exclude:
  - CNAME
  - README.md
