// Generated by CoffeeScript 2.0.2


(function() {
  // this js is for main and default js (like things every page needs)
  var touch;

  touch = false;

  document.addEventListener("DOMContentLoaded", function() {
    var error;
    try {
      // ---------------------------------------------------
      // check if it has touch (mobile)
      document.createEvent('TouchEvent');
      document.documentElement.className += " touch";
      touch = true;
    } catch (error1) {
      error = error1;
      document.documentElement.className += " no-touch";
    }
    // getter for touch var to know if it has touch
    return window.hasTouch = function() {
      return touch;
    };
  });

  document.addEventListener("DOMContentLoaded", function() {
    var state;
    // -----------------------------------------
    // footer reposition when window resize
    state = true;
    window.footerReposition = function() {
      var $footer;
      $footer = $('.footer');
      if ($('body').height() + $footer.outerHeight() + $footer.height() > $(window).outerHeight()) {
        if (state) {
          $footer.addClass('content-footer');
          // $footer.fadeOut 300, ->
          //   $footer.addClass 'content-footer'
          //   $footer.fadeIn 400
          return state = false;
        }
      } else {
        if (!state) {
          $footer.removeClass('content-footer');
          // $footer.fadeOut 300, ->
          //   $footer.removeClass 'content-footer'
          //   $footer.fadeIn 400
          return state = true;
        }
      }
    };
    return $(window).resize(footerReposition);
  });

  $(window).on('load', function() {
    return footerReposition();
  });

  document.addEventListener("DOMContentLoaded", function() {
    var timeoutFunctions;
    console.log($('body').height());
    // ---------------------------------------------------------------
    // functions for mobile toggle controls
    if (hasTouch()) {
      $('.slideshow').removeClass('hasHover');
      $('.slideshow').on('touchend', function(event) {
        var $buttons, $this;
        $this = $(event.target).closest('.slideshow');
        $buttons = $($this).find('.button-wrapper');
        if ($buttons.hasClass('toggle')) {
          $buttons.removeClass('toggle');
          return;
        }
        $('.button-wrapper.toggle').removeClass('toggle');
        return $buttons.addClass('toggle');
      });
    }
    // ---------------------------------------------------------------
    timeoutFunctions = []; //holds the variables for timeout funtion

    // function changes slides in targetSlideshow
    window.changeSlide = function(change = 1, targetSlideshow, manuelChange = false) {
      var current, index, length, speed;
      targetSlideshow = $(targetSlideshow).closest('.slideshow');
      current = parseInt(targetSlideshow.attr('current'));
      length = targetSlideshow.data('length');
      index = parseInt(targetSlideshow.data('index'));
      targetSlideshow.find('[data-pos=' + current + ']').removeClass('active');
      current = current + change < 0 ? length - 1 : (current + change) % length;
      targetSlideshow.find('[data-pos=' + current + ']').addClass('active');
      targetSlideshow.attr('current', current);
      if (manuelChange) { // pause if manuel change
        clearTimeout(timeoutFunctions[index]);
        targetSlideshow.addClass('pause');
        return '';
      }
      speed = targetSlideshow.data('speed');
      return timeoutFunctions[index] = setTimeout(changeSlide, speed, change, targetSlideshow, manuelChange);
    };
    // autostart slidesshows who do not have pause
    // and mobile setup
    return $('.slideshow').each(function(index) {
      var timeoutFunction;
      $(this).attr('data-index', index);
      timeoutFunction = '';
      timeoutFunctions.push(timeoutFunction);
      if ($(this).hasClass('pause')) {
        return;
      }
      changeSlide(1, this, false);
    });
  });
}).call(this);

function whatsapp(formType){
  name = formType=='pray' ? $('#prayName').val() : $('#tesName').val()
  email = formType=='pray' ? $('#prayEmail').val() : ''
  number = formType=='pray' ? $('#prayNum').val() : $('#tesNum').val()
  text = formType=='pray' ? $('#prayText').val() : $('#tesText').val()
  if (formType=='pray')
  {
    var u = encodeURI('Hi habtamu my name is: '+ name + ', My email adress is : '+ email + ' ,  My phone number is : ' + number + ',  Here is my pray request text: ' + text )
  }else{
    var u = encodeURI('Hi habtamu my name is: '+ name + ', My email adress is : '+ email + ' ,  My phone number is : ' + number + ',  Here is my testimony: ' + text )
  }


  window.location =("https://api.whatsapp.com/send?phone=13478397738&text="+ u)
}

